-- Control plane v1 for the indicator laboratory.
-- This migration is intentionally isolated from lab_automatizado.

create schema if not exists lab_indicadores;

create table lab_indicadores.runs (
  id uuid primary key default gen_random_uuid(),
  run_key text not null unique,
  run_type text not null check (run_type in ('preflight', 'research')),
  status text not null default 'queued'
    check (status in ('queued', 'claimed', 'running', 'succeeded', 'failed', 'cancel_requested', 'cancelled')),
  dataset_manifest text,
  config jsonb not null default '{}'::jsonb,
  owner_id uuid references auth.users(id) on delete set null,
  requested_by text,
  worker_id text,
  error_message text,
  heartbeat_at timestamptz,
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table lab_indicadores.commands (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references lab_indicadores.runs(id) on delete cascade,
  command_type text not null check (command_type in ('start_run', 'cancel_run')),
  status text not null default 'queued'
    check (status in ('queued', 'claimed', 'completed', 'failed', 'cancelled')),
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  owner_id uuid references auth.users(id) on delete set null,
  requested_by text,
  claimed_by text,
  error_message text,
  requested_at timestamptz not null default now(),
  claimed_at timestamptz,
  completed_at timestamptz,
  constraint start_run_requires_run
    check (command_type <> 'start_run' or run_id is not null)
);

create table lab_indicadores.events (
  id bigint generated by default as identity primary key,
  run_id uuid not null references lab_indicadores.runs(id) on delete cascade,
  event_type text not null,
  message text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table lab_indicadores.artifacts (
  id uuid primary key default gen_random_uuid(),
  run_id uuid not null references lab_indicadores.runs(id) on delete cascade,
  artifact_type text not null,
  uri text not null,
  sha256 text check (sha256 is null or sha256 ~ '^[0-9a-f]{64}$'),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table lab_indicadores.workers (
  worker_id text primary key,
  status text not null default 'offline'
    check (status in ('online', 'busy', 'offline', 'degraded')),
  capabilities jsonb not null default '[]'::jsonb,
  version text,
  last_heartbeat_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index commands_queue_idx
  on lab_indicadores.commands (status, requested_at)
  where status = 'queued';

create index runs_status_created_idx
  on lab_indicadores.runs (status, created_at desc);

create index events_run_created_idx
  on lab_indicadores.events (run_id, created_at desc);

create index artifacts_run_created_idx
  on lab_indicadores.artifacts (run_id, created_at desc);

create or replace function lab_indicadores.touch_updated_at()
returns trigger
language plpgsql
set search_path = lab_indicadores, pg_catalog
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger runs_touch_updated_at
before update on lab_indicadores.runs
for each row execute function lab_indicadores.touch_updated_at();

create trigger workers_touch_updated_at
before update on lab_indicadores.workers
for each row execute function lab_indicadores.touch_updated_at();

create or replace function lab_indicadores.enqueue_preflight(
  p_idempotency_key text,
  p_run_key text default null,
  p_requested_by text default null,
  p_dataset_manifest text default 'indicator-lab-smoke-v1',
  p_config jsonb default '{}'::jsonb
)
returns table (run_id uuid, command_id uuid, existing boolean)
language plpgsql
security invoker
set search_path = lab_indicadores, pg_catalog
as $$
declare
  v_owner_id uuid := auth.uid();
  v_run_id uuid;
  v_command_id uuid;
begin
  if nullif(trim(p_idempotency_key), '') is null then
    raise exception 'idempotency key is required';
  end if;

  select c.run_id, c.id
    into v_run_id, v_command_id
  from lab_indicadores.commands c
  where c.idempotency_key = p_idempotency_key;

  if found then
    return query select v_run_id, v_command_id, true;
    return;
  end if;

  insert into lab_indicadores.runs (
    run_key, run_type, dataset_manifest, config, owner_id, requested_by
  ) values (
    coalesce(nullif(trim(p_run_key), ''), p_idempotency_key),
    'preflight',
    p_dataset_manifest,
    coalesce(p_config, '{}'::jsonb),
    v_owner_id,
    p_requested_by
  )
  returning id into v_run_id;

  insert into lab_indicadores.commands (
    run_id, command_type, idempotency_key, payload, owner_id, requested_by
  ) values (
    v_run_id,
    'start_run',
    p_idempotency_key,
    jsonb_build_object('run_type', 'preflight', 'dataset_manifest', p_dataset_manifest),
    v_owner_id,
    p_requested_by
  )
  returning id into v_command_id;

  insert into lab_indicadores.events (run_id, event_type, message, payload)
  values (
    v_run_id,
    'run_queued',
    'Preflight queued',
    jsonb_build_object('command_id', v_command_id, 'idempotency_key', p_idempotency_key)
  );

  return query select v_run_id, v_command_id, false;
end;
$$;

create or replace function lab_indicadores.claim_next_command(p_worker_id text)
returns table (
  command_id uuid,
  run_id uuid,
  command_type text,
  payload jsonb,
  dataset_manifest text
)
language plpgsql
security invoker
set search_path = lab_indicadores, pg_catalog
as $$
begin
  return query
  with next_command as (
    select c.id
    from lab_indicadores.commands c
    where c.status = 'queued'
      and c.command_type = 'start_run'
    order by c.requested_at, c.id
    for update skip locked
    limit 1
  ), claimed as (
    update lab_indicadores.commands c
    set status = 'claimed',
        claimed_by = p_worker_id,
        claimed_at = now()
    from next_command n
    where c.id = n.id
    returning c.id, c.run_id, c.command_type, c.payload
  )
  update lab_indicadores.runs r
  set status = 'claimed',
      worker_id = p_worker_id,
      heartbeat_at = now(),
      updated_at = now()
  from claimed c
  where r.id = c.run_id
  returning c.id, c.run_id, c.command_type, c.payload, r.dataset_manifest;
end;
$$;

create or replace function lab_indicadores.record_event(
  p_run_id uuid,
  p_event_type text,
  p_message text,
  p_payload jsonb default '{}'::jsonb
)
returns bigint
language sql
security invoker
set search_path = lab_indicadores, pg_catalog
as $$
  insert into lab_indicadores.events (run_id, event_type, message, payload)
  values (p_run_id, p_event_type, p_message, coalesce(p_payload, '{}'::jsonb))
  returning id;
$$;

alter table lab_indicadores.runs enable row level security;
alter table lab_indicadores.commands enable row level security;
alter table lab_indicadores.events enable row level security;
alter table lab_indicadores.artifacts enable row level security;
alter table lab_indicadores.workers enable row level security;

create policy runs_owner_select
  on lab_indicadores.runs for select to authenticated
  using ((select auth.uid()) = owner_id);

create policy commands_owner_select
  on lab_indicadores.commands for select to authenticated
  using ((select auth.uid()) = owner_id);

create policy commands_owner_insert
  on lab_indicadores.commands for insert to authenticated
  with check ((select auth.uid()) = owner_id);

create policy events_owner_select
  on lab_indicadores.events for select to authenticated
  using (exists (
    select 1 from lab_indicadores.runs r
    where r.id = run_id and r.owner_id = (select auth.uid())
  ));

create policy artifacts_owner_select
  on lab_indicadores.artifacts for select to authenticated
  using (exists (
    select 1 from lab_indicadores.runs r
    where r.id = run_id and r.owner_id = (select auth.uid())
  ));

create policy workers_authenticated_select
  on lab_indicadores.workers for select to authenticated
  using (true);

grant usage on schema lab_indicadores to authenticated, service_role;
grant select on all tables in schema lab_indicadores to authenticated;
grant insert on lab_indicadores.commands to authenticated;
grant all privileges on all tables in schema lab_indicadores to service_role;
grant all privileges on all sequences in schema lab_indicadores to service_role;
grant execute on function lab_indicadores.enqueue_preflight(text, text, text, text, jsonb)
  to authenticated, service_role;
grant execute on function lab_indicadores.claim_next_command(text)
  to service_role;
grant execute on function lab_indicadores.record_event(uuid, text, text, jsonb)
  to service_role;

comment on schema lab_indicadores is
  'Exclusive control plane for the WDO/WIN indicator research laboratory.';
